#!/bin/bash

#SBATCH --job-name boltzmpi
#SBATCH --partition cpu
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 28
#SBATCH --cpus-per-task 1
#SBATCH --time 00:05:00
#SBATCH --mem-per-cpu 100M
#SBATCH --output boltzmpi.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
srun ./boltzmpi inputs/input_1024x1024.params obstacles/obstacles_1024x1024.dat

